<!DOCTYPE html>
<html lang="es">
<head>
    <title>DAW - AMAZON</title>
    <meta charset="UTF-8">
    <meta name="author" content="Héctor Pascual Marín">
    <link rel="stylesheet" href="css/amazon.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
   
</head>

<body>
    <header>
    <nav class="navbar navbar-expand navbar-dark">
            <div class="container-fluid">
            <a class="navbar-brand" href="#"><img src="imgs/logo.jpg" alt="Mi web de móviles"></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link" aria-current="page" href="index.php">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" aria-current="page" href="form_movil.php">Añadir móvil</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>